---
version: '3.4'
services:

  besu:
    image: hyperledger/besu:${BESU_VERSION}
    volumes:
      - ./config/besu:/opt/besu/conf/
      - ./data/besu:/opt/besu/data/
    command: [
      "--config-file=/opt/besu/conf/besu.conf",
      "--miner-enabled=true",
      "--miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
    ]
    ports:
      - 8545:8545
      - 8546:8546
      - 8547:8547
      - 30303:30303/tcp
      - 30303:30303/udp
    networks:
      main:
        ipv4_address: 172.24.2.11

  besu2:
    image: hyperledger/besu:${BESU_VERSION}
    depends_on:
      - besu
    volumes:
      - ./config/besu2:/opt/besu/conf/
      - ./data/besu2:/opt/besu/data/
    command: [
      "--config-file=/opt/besu/conf/besu.conf",
      "--miner-enabled=true",
      "--miner-coinbase=0x627306090abaB3A6e1400e9345bC60c78a8BEf57"
    ]
    ports:
      - 8548:8545
      - 8549:8546
      - 8550:8547
      - 30304:30304/tcp
      - 30304:30304/udp
    networks:
      main:
        ipv4_address: 172.24.2.12

  besu3:
    image: hyperledger/besu:${BESU_VERSION}
    depends_on:
      - besu
      - besu2
    volumes:
      - ./config/besu3:/opt/besu/conf/
      - ./data/besu3:/opt/besu/data/
    command: [
      "--config-file=/opt/besu/conf/besu.conf",
      "--miner-enabled=true",
      "--miner-coinbase=0xf17f52151EbEF6C7334FAD080c5704D77216b732"
      ]
    ports:
      - 8551:8545
      - 8552:8546
      - 8553:8547
      - 30305:30305/tcp
      - 30305:30305/udp
    networks:
      main:
        ipv4_address: 172.24.2.13

  alethio:
    image: "alethio/ethereum-lite-explorer"
    environment: 
      - APP_NODE_URL=http://localhost:8545
    depends_on:
      - besu
    ports:
      - 25000:80/tcp
    networks:
      main:
        ipv4_address: 172.24.2.21

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    networks:
      main:
        ipv4_address: 172.24.2.22

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    networks:
      main:
        ipv4_address: 172.24.2.23

volumes:
  public-keys:

  prometheus:

  grafana:

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.2.0/27